1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [ ]:
import numpy as np

A = np.array([[1,2,3]])
B = np.array([[4,5,6]])
# Stack vertically (one on top of the other)
vertical_stack = np.vstack((A, B))

# Stack horizontally (side by side)
horizontal_stack = np.hstack((A, B))

print("Array A:\n", A)
print("\nArray B:\n", B)
print("\nVertically Stacked Array:\n", vertical_stack)
print("\nHorizontally Stacked Array:\n", horizontal_stack)

[[1 2 3]]
[[4 5 6]]
Array A:
 [[1 2 3]]

Array B:
 [[4 5 6]]

Vertically Stacked Array:
 [[1 2 3]
 [4 5 6]]

Horizontally Stacked Array:
 [[1 2 3 4 5 6]]


Find common elements between A and B. [Hint : Intersection of two sets]

In [6]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[4, 5, 6],
              [7, 8, 9]])

# Find common elements using set intersection
common_elements = np.intersect1d(A, B)

print("Common elements between A and B:", common_elements)

Common elements between A and B: [4 5 6]


Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [7]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
indices = np.where((A >= 5) & (A <= 10))
result_where = A[indices]
print("Original array:", A)
print("Values between 5 and 10 (np.where):", result_where)

Original array: [[1 2 3]
 [4 5 6]]
Values between 5 and 10 (np.where): [5 6]


Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [8]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Apply filtering conditions
filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]

print(filtered_rows)


[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]
